const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=require('path').resolve(__dirname,'..');
const source=fs.readFileSync(root+'/index.html','utf8');
const script=[...source.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].at(-1)[1];
const els=new Map();const el=id=>{if(!els.has(id))els.set(id,{value:'',textContent:'',innerHTML:'',disabled:false,style:{},classList:{add(){},remove(){},toggle(){return false}},addEventListener(){},focus(){},select(){}});return els.get(id)};
let response={ok:true,activities:[]};
const calls=[];
const ctx={window:{BARRIOS_API_URL:'https://example.test/exec'},document:{getElementById:el,querySelectorAll(){return []},body:el('body'),addEventListener(){}},localStorage:{getItem(){},setItem(){},removeItem(){}},console:{error(){}},alert(){},confirm(){return true},setTimeout(){},clearTimeout(){},AbortController,URL,Set,Date,Promise,fetch:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>response}}};vm.createContext(ctx);vm.runInContext(script,ctx);
(async()=>{
 await Promise.resolve();await Promise.resolve();
 assert.equal(ctx.esc('<img src=x onerror="boom"> & \'q\''),'&lt;img src=x onerror=&quot;boom&quot;&gt; &amp; &#039;q&#039;');
 assert.equal(ctx.safeUrl('javascript:alert(1)'),'');assert.equal(ctx.safePhoto('data:text/html;base64,AAAA'),'');assert.equal(ctx.safeColor('red;position:fixed'),'#0092DD');
 assert.equal(ctx.fromRow({photos:'null'}).photos.length,0);assert.equal(ctx.fromRow({photos:['https://example.com/a.jpg']}).photos.length,1);
 assert.deepEqual(Array.from(ctx.dateToIso('30 DE SEPTIEMBRE Y 1 DE OCTUBRE')),[new Date().getFullYear()+'-09-30',new Date().getFullYear()+'-10-01']);
 ctx.acts=[{id:1,title:'<img src=x onerror=alert(1)>',day:'SÁBADO',date:'1 DE OCTUBRE',color:'red;display:none',photos:[],link:'javascript:alert(1)'}];ctx.renderLanding();
 assert(!el('landing').innerHTML.includes('onerror=alert(1)>'));assert(!el('landing').innerHTML.includes('javascript:'));assert(el('landing').innerHTML.includes('&lt;img'));
 ctx.acts[0].active=false;ctx.renderLanding();assert(el('landing').innerHTML.includes('No hay actividades'));
 ctx.acts=[{id:1,title:'Original',color:'#0092DD',photos:[]}];ctx.adminAuthorized=true;ctx.adminPassword='test-only';response={ok:false,error:'network error'};
 await ctx.saveActs({id:1,title:'Edited'}).catch(()=>{});assert.equal(ctx.acts[0].title,'Original');
 await ctx.delAct('1');assert.equal(ctx.acts.length,1);
 response={ok:true};await ctx.delAct('1');assert.equal(ctx.acts.length,0);
 ctx.adminAuthorized=true;ctx.adminPassword='test-only';response={ok:false,error:'timeout'};el('f-title').value='Retry';el('f-date1').value='2026-10-01';
 ctx.save();await new Promise(setImmediate);const firstDraft=ctx.draftId;ctx.save();await new Promise(setImmediate);assert.equal(ctx.draftId,firstDraft);assert(firstDraft);ctx.cancelEdit();assert.equal(ctx.draftId,null);
 ctx.adminAuthorized=false;ctx.adminPassword='';await assert.rejects(ctx.saveActs({id:'2'}));
 el('pass-input').value='bad';response={ok:false,error:'Contraseña incorrecta'};await ctx.tryAuth();assert.equal(ctx.adminAuthorized,false);assert.equal(ctx.adminPassword,'');
 el('pass-input').value='test-only';response={ok:true,activities:[]};await ctx.tryAuth();assert.equal(ctx.adminAuthorized,true);ctx.logoutAdmin();assert.equal(ctx.adminAuthorized,false);assert.equal(ctx.adminPassword,'');
 assert(!/var PASS=|SB_PUBLIC_ANON_KEY|supabase-js|sessionStorage/.test(source));
 console.log('PASS: password validated remotely, failed login, logout and unauthenticated writes');
 console.log('PASS: escaping, URL/color validation, photo formats, date ranges, visible counts, failed saves/deletes and numeric IDs');
 const backend=fs.readFileSync(root+'/apps-script/Code.gs','utf8');let locked=false,lockCalls=0;
 const rows=[['id','barrio','nombre','descripcion','album_url','activo','created_at'],['a','Jazmín','Activity','','https://photos.app.goo.gl/test',true,'date']];
 const homeRows=[['id','title','day','date','punto','descripcion','link','color','photos','active','created_at']];
 function mockSheet(data){return{getDataRange(){return{getValues(){return data}}},getLastRow(){return data.length},appendRow(r){assert(locked);data.push(r)},deleteRow(i){assert(locked);data.splice(i-1,1)},getRange(r,c,n=1){return{getValues(){return data.slice(r-1,r-1+n).map(x=>[x[c-1]])},getValue(){return data[r-1][c-1]},setValues(values){assert(locked);values.forEach((v,i)=>data[r-1+i]=v)}}}};}
 const sheet=mockSheet(rows),homeSheet=mockSheet(homeRows);
 const bc={SpreadsheetApp:{openById(){return{getSheetByName(name){return name==='Portada'?homeSheet:sheet}}}},LockService:{getScriptLock(){return{waitLock(){locked=true;lockCalls++},releaseLock(){locked=false}}}},PropertiesService:{getScriptProperties(){return{getProperty(name){return name==='ADMIN_PASSWORD'?'test-only':name==='SPREADSHEET_ID'?'test-sheet':null}}}},Utilities:{getUuid(){return 'new'}},ContentService:{MimeType:{JSON:'json'},createTextOutput(x){return{setMimeType(){return JSON.parse(x)}}}},Date};vm.createContext(bc);vm.runInContext(backend,bc);
 assert.equal(bc.doGet().ok,true);assert.equal(bc.doPost().ok,false);
 const post=b=>bc.doPost({postData:{contents:JSON.stringify({password:'test-only',...b})}});
 assert.equal(post({action:'update',id:'a',barrio:'Jazmín',nombre:'=danger()',descripcion:'',albumUrl:'https://photos.app.goo.gl/test'}).ok,true);assert.equal(rows[1][2],"'=danger()");assert(!locked);
 assert.equal(post({action:'delete',id:'a'}).ok,true);assert.equal(rows.length,1);assert.equal(lockCalls,2);assert(!locked);
 assert.equal(post({action:'create',barrio:'Jazmín',nombre:'Name',albumUrl:'https://drive.google.com.evil.test/x'}).ok,false);assert(!locked);
 const activity={id:'home-1',title:'=FORMULA()',day:'SÁBADO',date:'1 DE OCTUBRE',punto:'Oficina',desc:'Descripción',link:'https://example.com',color:'#0092DD',photos:['https://example.com/photo.jpg'],active:true};
 assert.equal(bc.doPost({postData:{contents:JSON.stringify({action:'homeSave',activity,password:'wrong'})}}).ok,false);assert.equal(homeRows.length,1);
 assert.equal(post({action:'homeSave',activity}).ok,true);assert.equal(homeRows.length,2);assert.equal(homeRows[1][1],"'=FORMULA()");assert(!locked);
 assert.equal(bc.doGet({parameter:{action:'homeList'}}).activities.length,1);
 assert.equal(post({action:'homeSave',activity:{...activity,active:false}}).ok,true);assert.equal(bc.doGet({parameter:{action:'homeList'}}).activities.length,0);
 assert.equal(post({action:'homeAdminList'}).activities.length,1);
 assert.equal(post({action:'homeSave',activity:{...activity,id:'=formula()'}}).ok,false);
 assert.equal(post({action:'homeSave',activity:{...activity,photos:['javascript:alert(1)']}}).ok,false);assert(!locked);
 assert.equal(post({action:'homeDelete',id:'home-1'}).ok,true);assert.equal(homeRows.length,1);
 assert.equal(post({action:'homeDelete',id:'home-1'}).ok,false);assert(!locked);
 bc.UrlFetchApp={fetch(){return{getContentText(){return fs.readFileSync(root+'/data/actividades.json','utf8')}}}};
 bc.importarPortadaInicial();assert.equal(homeRows.length,5);assert(!locked);assert.throws(()=>bc.importarPortadaInicial());assert.equal(homeRows.length,5);assert(!locked);
 console.log('PASS: initial import preserves all four activities and prevents duplicate imports');
 console.log('PASS: home API authorization, create/update/delete, active filters and photo validation');
 console.log('PASS: backend malformed requests, mutation locks, formula escaping and album host validation');
})().catch(e=>{console.error(e);process.exitCode=1});
