const fs=require('fs'),vm=require('vm'),assert=require('assert');
const root=require('path').resolve(__dirname,'..');
const source=fs.readFileSync(root+'/index.html','utf8');
const script=[...source.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].at(-1)[1];
const els=new Map();const el=id=>{if(!els.has(id))els.set(id,{value:'',textContent:'',innerHTML:'',disabled:false,style:{},classList:{add(){},remove(){},toggle(){return false}},addEventListener(){},focus(){},select(){}});return els.get(id)};
let response={data:[],error:null};const db={from(){return {select(){return {order(){return Promise.resolve(response)}}},upsert(){return Promise.resolve(response)},delete(){return{eq(){return Promise.resolve(response)}}}}}};
const ctx={window:{supabase:{createClient(){return db}}},document:{getElementById:el,querySelectorAll(){return []},body:el('body'),addEventListener(){}},localStorage:{getItem(){},setItem(){},removeItem(){}},sessionStorage:{getItem(){},setItem(){}},console:{error(){}},alert(){},confirm(){return true},setTimeout(){},URL,Set,Date,Promise};vm.createContext(ctx);vm.runInContext(script,ctx);
(async()=>{
 await Promise.resolve();await Promise.resolve();
 assert.equal(ctx.esc('<img src=x onerror="boom"> & \'q\''),'&lt;img src=x onerror=&quot;boom&quot;&gt; &amp; &#039;q&#039;');
 assert.equal(ctx.safeUrl('javascript:alert(1)'),'');assert.equal(ctx.safePhoto('data:text/html;base64,AAAA'),'');assert.equal(ctx.safeColor('red;position:fixed'),'#0092DD');
 assert.equal(ctx.fromRow({photos:'null'}).photos.length,0);assert.equal(ctx.fromRow({photos:['https://example.com/a.jpg']}).photos.length,1);
 assert.deepEqual(Array.from(ctx.dateToIso('30 DE SEPTIEMBRE Y 1 DE OCTUBRE')),[new Date().getFullYear()+'-09-30',new Date().getFullYear()+'-10-01']);
 ctx.acts=[{id:1,title:'<img src=x onerror=alert(1)>',day:'SÁBADO',date:'1 DE OCTUBRE',color:'red;display:none',photos:[],link:'javascript:alert(1)'}];ctx.renderLanding();
 assert(!el('landing').innerHTML.includes('onerror=alert(1)>'));assert(!el('landing').innerHTML.includes('javascript:'));assert(el('landing').innerHTML.includes('&lt;img'));
 ctx.acts[0].active=false;ctx.renderLanding();assert(el('landing').innerHTML.includes('No hay actividades'));
 ctx.acts=[{id:1,title:'Original',color:'#0092DD',photos:[]}];response={error:{message:'network error'}};
 await ctx.saveActs({id:1,title:'Edited'}).catch(()=>{});assert.equal(ctx.acts[0].title,'Original');
 await ctx.delAct('1');assert.equal(ctx.acts.length,1);
 response={error:null};await ctx.delAct('1');assert.equal(ctx.acts.length,0);
 console.log('PASS: escaping, URL/color validation, photo formats, date ranges, visible counts, failed saves/deletes and numeric IDs');
 const backend=fs.readFileSync(root+'/apps-script/Code.gs','utf8');let locked=false,lockCalls=0,rows=[['id','barrio','nombre','descripcion','album_url','activo','created_at'],['a','Jazmín','Activity','','https://photos.app.goo.gl/test',true,'date']];
 const sheet={getDataRange(){return{getValues(){return rows}}},getLastRow(){return rows.length},appendRow(r){rows.push(r)},deleteRow(i){assert(locked);rows.splice(i-1,1)},getRange(r,c,n=1){return{getValues(){return rows.slice(r-1,r-1+n).map(x=>[x[c-1]])},getValue(){return rows[r-1][c-1]},setValues(values){assert(locked);rows[r-1]=values[0]}}}};
 const bc={SpreadsheetApp:{openById(){return{getSheetByName(){return sheet}}}},LockService:{getScriptLock(){return{waitLock(){locked=true;lockCalls++},releaseLock(){locked=false}}}},PropertiesService:{getScriptProperties(){return{getProperty(){return 'test-only'}}}},Utilities:{getUuid(){return 'new'}},ContentService:{MimeType:{JSON:'json'},createTextOutput(x){return{setMimeType(){return JSON.parse(x)}}}},Date};vm.createContext(bc);vm.runInContext(backend,bc);
 assert.equal(bc.doGet().ok,true);assert.equal(bc.doPost().ok,false);
 const post=b=>bc.doPost({postData:{contents:JSON.stringify({password:'test-only',...b})}});
 assert.equal(post({action:'update',id:'a',barrio:'Jazmín',nombre:'=danger()',descripcion:'',albumUrl:'https://photos.app.goo.gl/test'}).ok,true);assert.equal(rows[1][2],"'=danger()");assert(!locked);
 assert.equal(post({action:'delete',id:'a'}).ok,true);assert.equal(rows.length,1);assert.equal(lockCalls,2);assert(!locked);
 assert.equal(post({action:'create',barrio:'Jazmín',nombre:'Name',albumUrl:'https://drive.google.com.evil.test/x'}).ok,false);assert(!locked);
 console.log('PASS: backend malformed requests, mutation locks, formula escaping and album host validation');
})().catch(e=>{console.error(e);process.exitCode=1});
